config/routes.rb
Rails.application.routes.draw do
  
  resources :shots do
    resources :comments 
    member do
      put 'like', to: "shots#like"
      put 'unlike', to: "shots#unlike"
    end
  end
  devise_for :users, controllers:{registrations: 'registrations'}
  root 'shots#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :shot
end

app/models/shot.rb
class Shot < ApplicationRecord  
    acts_as_votable
    is_impressionable
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    def default_image
        "https://via.placeholder.com/150x150?text=Default+Image"
    end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shots, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    #on recupere dans une variable shot , le shot par son id
   @shot = Shot.find(params[:shot_id])
    #on recupere dans une variable comment ,le commentaire a creer par le shot_id avec les comments_params requis( name & cotent)
   @comment = @shot.comments.create(comment_params)
    # on assimile le curent_user id à user_id 
   @comment.user_id = current_user.id
   #on save la requete 
   @comment.save!
   #on redirige vers le shot
   redirect_to shot_path(@shot)
  end

  def destroy
    #on recupere dans une variable shot , le shot par son id
    @shot = Shot.find(params[:shot_id])
    #on recupere dans une variable comment , le commentaire a supprimer , par son id
    @comment = @shot.comments.find(params[:id])
    #on detruit le commentaire
    @comment.destroy
    #on redirige vers le shot
    redirect_to shot_path(@shot)
  end

  private
  def comment_params
    #les paramaetre requis pour comment , name et content
    params.require(:comment).permit(:name, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end


end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]
  impressionist actions: [:show]

  # GET /shots
  def index
    @shots = Shot.all.order("created_at DESC")
  end

  # GET /shots/1
  def show
   
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  def create
    @shot = current_user.shots.create(shot_params)


    respond_to do |format|
      if @shot.save
        format.html { redirect_to root_path, notice: 'shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

    
  # PATCH/PUT /shots/1
  def update
    respond_to do |format|
    if @shot.update(shot_params)
      format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
      format.json { render :show, status: :ok, location: @shot }   
    else
      format.html { render :edit }
      format.json { render json: @shot.errors, status: :unprocessable_entity }
    end
  end
end
  # DELETE /shots/1
  def destroy
    @shot.destroy
    respond_to do |format|
    format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def like
  @shot.liked_by current_user
  respond_to do |format|
    format.html { redirect_back fallback_location: root_path }
    format.js { render layout: false }
  end
end

def unlike
  @shot.unliked_by current_user
  respond_to do |format|
    format.html { redirect_back fallback_location: root_path }
    format.js { render layout: false }
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/comments/_comment.html.erb
<% #on fais un foreach sur comment %>
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.try(:email), alt: comment.user.try(:email), gravatar: { size: 48 }) %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.try(:name) %></strong>
          <div><%= comment.content %></div>
          <br>
          <small><a>Like</a> · <%= comment.created_at.try(:hour) %> hrs</small>
          
        </p>
        
      </div>
    </div>
    <% #si un utilisateur est connecté et que l'utilisateur courrant à le meme id que l'utilisateur du commentaire %>
    <% if (user_signed_in? && (current_user.id == comment.user_id)) %>
       <%= link_to 'Delete', [comment.shot, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@shot, @shot.comments.build]) do |f| %>
    
<div class="box">
<div class="media-content">
<div class="content">
        <%= f.input :content,
        input_html: {class: 'textarea is-black'},
        wrapper: false,
        label_html: {class: 'label'}
        %>
        </br>
        <%= f.button :submit, "Laisser un commentaire", class:"button" %>
        </div>
        </div>
</div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>DribbbleClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  
  <%= link_to root_path, class: "navbar-item" do %>
    <h1 class="title is-5">Dribbble</h1>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Shots
      </a>  
    </div>
    <div class="navbar-end">

      <div class="navbar-item">

        <div class="buttons">


          <% if user_signed_in? %>
          <p class="control"><%= link_to 'Nouveau Shot', new_shot_path, class: "button is-black " %></p>
          <p class="control"><%= link_to 'Se déconnecter ', destroy_user_session_path, method: :delete, class: 'button is-black' %></p>
          <p class="control"><%= link_to "Editer #{current_user.name}", edit_user_registration_path, class: 'button is-black' %></p>
          <% else %>
          <p class="control"><%= link_to 'Se connecter', new_user_session_path, class: 'button is-black'  %></p>
          <p class="control"><%= link_to "S'inscrire", new_user_registration_path, class: "button is-black"  %></p>     
          <% end %>
        
        
        </div>
      </div>
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
  
</html>

app/views/shots/_form.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered ">
      <div class="column is-4">
       
        <%= simple_form_for(@shot) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="field">
              <div class="control">
                <%= f.input :title,
                  required: true,
                  wrapper: false,
                  input_html: { class: "input ", autocomplete: "" },
                  label_html: {class: "label has-text-black"}
                  %>
              </div>
          </div>  

          <div class="field">
              <div class="control">
                <%= f.input :description,
                  required: true,
                  wrapper: false,
                  input_html: { class: "input", autocomplete: "" },
                  label_html: {class: "label has-text-black"}
                  %>
              </div>
          </div> 

          <div class="field">   
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>

          <div class="form-actions">
            <%= f.button :submit , class: 'button' %>
          </div

        <% end %>
         

      

        </div>
    </div>
  </div>
</div>

app/views/shots/edit.html.erb
<div class="section is-centered">
    <div class="container">
        <div class="columns is-centered">
            <h2 class="title has-text-black is-2">Modifier Shot</h2></br> 
        </div>
    </div>
</div>


<%= render 'form', shot: @shot %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<br />

<div class="section ">
    <div class="container ">
        <div class="columns is-mobile is-multiline ">
            <% #on fais un foreach sur shot %>
            <% @shots.each do |shot| %>
            <div class="column  is-2-desktop is-two-fifths-mobile ">
                <div class="card">
                    <div class="column is-full padding0">
                        <figure class="image is-150x150">
                            <%= image_tag shot.image.thumb.url || shot.default_image %>
                        </figure>
                    </div>
                    <div class="column is-full">

                        <p><span class="icon"><i class="far fa-eye has-text-primary"></i></span><span class="subtitle is-7">
                                <%= shot.impressionist_count %> |
                                <%= shot.title %></span>
                        </p>
                        <span class="subtitle is-7">
                            <%= link_to 'View', shot %></span>
                        <% if user_signed_in? && current_user.id === shot.user_id %>
                        <span class="subtitle is-7">
                            <%= link_to 'Edit', edit_shot_path(shot) %></span>
                        <span class="subtitle is-7">
                            <%= link_to 'Destroy', shot, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                        <% end %>
                        </p>
                    </div>

                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shots/new.html.erb
<div class="section is-centered">
    <div class="container">
        <div class="columns is-centered">
        <h2 class="title has-text-black is-2">Nouveau shot</h2></br> 
        </div>
    </div>
</div>


<%= render 'form', shot: @shot %>

<%= link_to 'Back', shots_path %>

app/views/shots/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<%= link_to 'Retour', shots_path %>

<div class="columns is-centered">

  <div class="column is-3 ">
    <figure class="image is-50x50">
      <%= image_tag @shot.image.thumb.url || @shot.default_image %>
    </figure>
    <div>
      <p>Nombre de vue:
        <%= @shot.impressionist_count %>
      </p>
      <div class="content">
        <p class="subtitle is-7">
          <%= @shot.description %>
        </p>
        <p class="subtitle is-6 ">
          <%= @shot.title %>
        </p>
      </div>
    </div>

    <div class="panel-block likes data">
      <% if user_signed_in? %>
      <% if current_user.liked? @shot %>
      <%= link_to unlike_shot_path(@shot), method: :put, class: "unlike_shot" do %>
      <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
      <span class="vote_count">
        <%= pluralize(@shot.get_likes.size, 'Like') %></span>
      <% end %>
      <% else %>
      <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
      <span class="icon"><i class="fa fa-heart"></i></span>
      <span class="vote_count">
        <%= pluralize(@shot.get_likes.size, 'Like') %></span>
      <% end %>
      <% end %>
      <% else %>
      <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
      <span class="icon"><i class="fa fa-heart"></i></span>
      <span class="vote_count">
        <%= pluralize(@shot.get_likes.size, 'Like') %></span>
      <% end %>
      <% end %>
    </div>



  </div>





  <div class="column is-5">
    <%= render 'comments/form' %>
    <% #compteur de commentaire %>
    <%= pluralize(@shot.comments.count, 'Commentaire')%>
    <%= render @shot.comments %>
  </div>

</div>